#!/usr/bin/env python3

# Poor Man's Sequencer
#
# Copyright (C) 2017 Remigiusz Dybka
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys, os

try:
	from pypms import pms
except ImportError:
	sys.path.append(__file__.replace("/bin/pms", "/lib/pms"))

from pypms import pms

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import GLib, Gtk, Gio

from mainwin import *
import randomcomposer

class PMSApp(Gtk.Application):
	def __init__(self):
		Gtk.Application.__init__(self, application_id = "com.github.rdybka.pms", 
			flags = Gio.ApplicationFlags.NON_UNIQUE)
		
	def do_activate(self):
		win = MainWin(self)
		
		if pms.start_error:
			self.quit()
			
		self.add_window(win)
		win.show_all()
		pms.play = True

def log_func(data):
	raise MemoryError("gotcha!")

class cfg:
	pass

if __name__ == "__main__":
	pms.start_error = None
	if pms.jack_start() != 0:
		pms.start_error = "you will need JACK for this"

	# move this stuff to proper configuration
	pms.cfg = cfg()
	#pms.cfg.seq_font = "Ubuntu Mono"
	pms.cfg.seq_font = "Roboto Mono Medium"
	#pms.cfg.seq_font = "Monospace"
	pms.cfg.seq_font_size = 16
	pms.cfg.seq_line_width = 1.0
	pms.cfg.highlight = 4
	pms.cfg.padding = 3
	#pms.cfg.colour = (.9, 1.0, .2)
	#pms.cfg.colour = (.6, .6, 1.0)
	pms.cfg.colour = (.4, 1.0, .4)
	pms.cfg.intensity_background = .3
	pms.cfg.intensity_txt = .7
	pms.cfg.intensity_txt_highlight = 1.0
	pms.cfg.intensity_lines = .6
	pms.cfg.pointer_opacity = .8
	
	randomcomposer.muzakize()

	try:
		app = PMSApp()

		app.run(sys.argv)
	except:
		pms.jack_stop()	
		sys.exit()

	# is this reliable? should we wait for module.mute == 0?
	pms.play = False
	
	pms.jack_stop()
